import { StyleSheet } from 'react-native';
import { hp, wp } from '../../enums/styleGuide';
export const styles = StyleSheet.create({
  Header: {
    width: '100%',
    height: '6.5%',
    justifyContent: 'center',
    backgroundColor: '#412160',
  },
  Headerview: {
    flexDirection: 'row',
    marginLeft: wp(5),
    justifyContent: 'space-between',
    width: '85%',
  },
  headerimage: {
    width: 20,
    height: 20,
    tintColor: '#FFFFFF',
    marginTop: wp(1),
  },
  headertext: {
    fontSize: wp(5),
    fontWeight: '700',
    color: '#fff',
  },
  View: {
    width: '90%',
    height: '6%',
    backgroundColor: '#D1A8F924',
    marginTop: wp(8),
    alignSelf: 'center',
    borderRadius: 9,
    justifyContent: 'center',
  },
  Text: {
    fontSize: wp(4),
    fontWeight: '600',
    color: '#412160',
  },
  Image: {
    tintColor: '#412160',
    width: 20,
    height: 20,
  },
  View1: {
    width: '90%',
    height: '6%',
    backgroundColor: '#FFFFFF',
    marginTop: wp(4),
    alignSelf: 'center',
    borderRadius: 9,
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  Mainview: {
    width: '90%',
    height: '55%',
    alignSelf: 'center',
    marginTop: wp(6),
    backgroundColor: '#FFFFFF',
    borderRadius: 9,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  view: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: wp(80),
    alignSelf: 'center',
    marginTop: wp(10),
  },

  text: {
    fontSize: wp(4),
    fontWeight: '700',
    color: '#412160',
  },
  text2: {
    fontSize: wp(4),
    fontWeight: '700',
    color: '#412160',
    marginTop: wp(2),
  },
  image: {
    width: 80,
    height: 80,
  },
  view2: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignSelf: 'center',
    width: '90%',
    marginTop: wp(2),
  },
  text3: {
    fontSize: wp(4),
    fontWeight: '700',
    color: '#412160',
    marginTop: wp(2),
    alignSelf: 'flex-end',
    marginRight: wp(2),
  },
  text4: {
    fontSize: wp(4),
    fontWeight: '700',
    color: '#C4C4C4',
    marginTop: wp(0),
    marginLeft: wp(5),
  },
  view3: {
    width: '90%',
    height: 0.3,
    backgroundColor: '#C4C4C4',
    marginTop: wp(2),
    alignSelf: 'center',
  },
  touchableview: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: wp(5),
    width: '90%',
    alignSelf: 'center',
  },
  touchable: {
    width: '35%',
    height: '38%',
    backgroundColor: '#17D406',
    justifyContent: 'center',
    borderRadius: wp(2),
  },
  touchabletext: {
    fontSize: wp(4),
    fontWeight: '500',
    alignSelf: 'center',
    color: '#fff',
  },
  touchable2: {
    width: '35%',
    height: '38%',
    backgroundColor: '#FD1919',
    justifyContent: 'center',
    borderRadius: wp(3),
  },
});
